services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=filelord01@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--api.dashboard=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.filelord.ir`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  
  core_api:
    image: ghcr.io/arian-nj/tix-core:${GIT_COMMIT_HASH}
    build:
      context: .
      dockerfile: core.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=4444"
      - "traefik.http.routers.web.rule=Host(`core.filelord.ir`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    secrets:
      - secret-key
      - db-url
    environment:
      - CORE_HTTP_PORT=4444
      - BASE_URL=https://core.filelord.ir
      - SECRET_KEY_FILE=/run/secrets/secret-key
      - DATABASE_URL_FILE=/run/secrets/db-url
      - RELEASE_MODE=dev
      - PROJECT_VERSION=${PROJECT_VERSION}
    deploy:
      update_config:
        order: start-first
  hokm4:
    build:
      context: .
      dockerfile: hokm4.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=4445"
      - "traefik.http.routers.web.rule=Host(`hokm4.filelord.ir`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    secrets:
      - secret-key
      - db-url
    environment:
      - CORE_HTTP_PORT=4445
      - BASE_URL=https://hokm4.filelord.ir
      - SECRET_KEY_FILE=/run/secrets/secret-key
      - DATABASE_URL_FILE=/run/secrets/db-url
      - RELEASE_MODE=dev
      - PROJECT_VERSION=${PROJECT_VERSION}

volumes:
  postgres_data:
  letsencrypt:

secrets:
  secret-key: 
    external: true
  db-url: 
    external: true