services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: game
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Keeps data persistent
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  core_api:
    image: ghcr.io/arian-nj/tix/core:latest
    build:
      context: .
      dockerfile: core.Dockerfile
    ports:
     - 4444:4444
    environment:
      - HTTP_PORT=${CORE_HTTP_PORT}
      - BASE_URL=${BASE_URL}
      - SecretKey=${SecretKey}
      - DATABASE_URL=${DATABASE_URL}
      - RELEASE_MODE=${RELEASE_MODE}
      - VERSION=${VERSION}
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db
  # hokm4:
  #   build:
  #     context: .
  #     dockerfile: hokm4.Dockerfile
  #   ports:
  #    - 127.0.0.1:4445:4445
  #   environment:
  #     - HTTP_PORT=${HOKM4_HTTP_PORT}
  #     - BASE_URL=${BASE_URL}
  #     - SecretKey=${SecretKey}
  #     - DATABASE_URL=${DATABASE_URL}
  #     - RELEASE_MODE=${RELEASE_MODE}
  #     - VERSION=${VERSION}

volumes:
  postgres_data:
