version: '3'

tasks:
  run_user:
    desc: run user service
    deps: [docker,gsqlc]
    dir: ./backend
    watch: true
    sources:
     - '**/*.go'
     - exclude: sqldb/*.go
    cmds:
      - go run ./cmd/user/.
      
  
  run_hokm_4:
    desc: run hokm 4 player service
    deps: [docker,gsqlc]
    dir: ./backend
    watch: true
    sources:
     - '**/*.go'
     - exclude: sqldb/*.go
    cmds:
      - go run ./cmd/hokm4/.
  
  clean_task:
    desc: clear task cache
    cmds:
      - rm -r .task

  kill:
    desc: kills process using 5432 port
    cmds:
      - sudo kill $(sudo lsof -t -i:5432)
  
  caddy:
    desc: run caddy 
    cmds:
      - caddy run

  docker:
    desc: docker up
    dir: ./backend
    cmds:
      - sudo docker compose up -d
  
  gsqlc:
    desc: generate sqlc files
    dir: ./backend
    cmds:
      - sqlc generate
  
  release:
      prompt:
       - This is a dangerous command Do You Know what are you doing ???
       - Are you sure?
      cmds:
      - echo 'dangerous command'

dotenv: ['backend/.env']

  