version: '3'

tasks:
  run_core:
    desc: run core service
    dir: ./backend
    deps: [clean_task,gsqlc]
    # watch: true
    # sources:
    #  - '**/*.go'
    #  - exclude: sqldb/*.go
    cmds:
      - CORE_HTTP_PORT=4444 BASE_URL=https://core.filelord.ir DATABASE_URL_FILE=postgres://pgadmin:pgpass@127.0.0.1:5432/game?sslmode=disable RELEASE_MODE=dev VERSION=0.2.0 PROJECT_VERSION=1.0.0 SecretKey=sdasfdgewfef go run ./cmd/core/.
      
  
  run_hokm_4:
    desc: run hokm 4 player service
    deps: [clean_task,gsqlc]
    dir: ./backend
    # watch: true
    # sources:
    #  - '**/*.go'
    #  - exclude: sqldb/*.go
    cmds:
      - HOKM4_HTTP_PORT=4445 BASE_URL=https://core.filelord.ir DATABASE_URL_FILE=postgres://pgadmin:pgpass@127.0.0.1:5432/game?sslmode=disable RELEASE_MODE=dev VERSION=0.2.0 PROJECT_VERSION=1.0.0 SecretKey=sdasfdgewfef go run ./cmd/hokm4/.
  
  clean_task:
    desc: clear task cache
    cmds:
      - rm -rf .task

  kill:
    desc: kills process using 5432 port
    cmds:
      - sudo kill $(sudo lsof -t -i:5432)
  
  caddy:
    desc: run caddy 
    cmds:
      - caddy run

  docker:
    desc: docker up
    dir: ./backend
    cmds:
      - docker compose up -d
  docker_down:
    desc: docker down
    dir: ./backend
    cmds:
      - sudo docker compose down
    
  gsqlc:
    desc: generate sqlc files
    dir: ./backend
    cmds:
      - sqlc generate
  
  export_pck:
    desc: export game content as pck
    dir: ./game
    cmds:
      - mkdir -p ../files/patches/
      - rm -f ../files/patches/*.pck
      - ~/Godot_v4.4-stable_linux.x86_64 --headless --export-pack AndroidPck ../files/patches/system.pck

  upload_s3_dev:
    desc: upload new version to s3
    dir: ./backend/tools/gos3
    cmds:
      - go run .

  release:
      prompt:
       - This is a dangerous command Do You Know what are you doing ???
       - Are you sure?
      cmds:
      - echo 'dangerous command'

dotenv: ['backend/.env']

  