// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hokm4_query.sql

package sqldb

import (
	"context"
)

const insertGamePlayer = `-- name: InsertGamePlayer :one
INSERT INTO game_player (player_id, game_id,team) VALUES ($1,$2,$3) RETURNING player_id, game_id, team
`

type InsertGamePlayerParams struct {
	PlayerID int
	GameID   int
	Team     int
}

func (q *Queries) InsertGamePlayer(ctx context.Context, arg InsertGamePlayerParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, insertGamePlayer, arg.PlayerID, arg.GameID, arg.Team)
	var i GamePlayer
	err := row.Scan(&i.PlayerID, &i.GameID, &i.Team)
	return i, err
}

const insertHokm4Game = `-- name: InsertHokm4Game :one
INSERT INTO hokm4_game DEFAULT VALUES RETURNING id, team_one_tricks_score, team_two_tricks_score
`

func (q *Queries) InsertHokm4Game(ctx context.Context) (Hokm4Game, error) {
	row := q.db.QueryRow(ctx, insertHokm4Game)
	var i Hokm4Game
	err := row.Scan(&i.ID, &i.TeamOneTricksScore, &i.TeamTwoTricksScore)
	return i, err
}

const insertTrick = `-- name: InsertTrick :one
INSERT INTO trick (game_id, hakem_index) VALUES ($1,$2) RETURNING trick_id, game_id, hokm, hakem_index, team_one_turn_score, team_two_turn_score
`

type InsertTrickParams struct {
	GameID     int
	HakemIndex int
}

func (q *Queries) InsertTrick(ctx context.Context, arg InsertTrickParams) (Trick, error) {
	row := q.db.QueryRow(ctx, insertTrick, arg.GameID, arg.HakemIndex)
	var i Trick
	err := row.Scan(
		&i.TrickID,
		&i.GameID,
		&i.Hokm,
		&i.HakemIndex,
		&i.TeamOneTurnScore,
		&i.TeamTwoTurnScore,
	)
	return i, err
}

const insertTurn = `-- name: InsertTurn :one
INSERT INTO turn (moves,trick_id) VALUES ($1,$2) RETURNING turn_id, trick_id, moves
`

type InsertTurnParams struct {
	Moves   string
	TrickID int
}

func (q *Queries) InsertTurn(ctx context.Context, arg InsertTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, insertTurn, arg.Moves, arg.TrickID)
	var i Turn
	err := row.Scan(&i.TurnID, &i.TrickID, &i.Moves)
	return i, err
}

const updateHokmTrick = `-- name: UpdateHokmTrick :exec
UPDATE trick SET hokm = $1 WHERE trick_id = $2
`

type UpdateHokmTrickParams struct {
	Hokm    int
	TrickID int
}

func (q *Queries) UpdateHokmTrick(ctx context.Context, arg UpdateHokmTrickParams) error {
	_, err := q.db.Exec(ctx, updateHokmTrick, arg.Hokm, arg.TrickID)
	return err
}

const updateTrickScores = `-- name: UpdateTrickScores :exec
UPDATE hokm4_game SET team_one_tricks_score = $1,team_two_tricks_score=$2 WHERE id = $3
`

type UpdateTrickScoresParams struct {
	TeamOneTricksScore int
	TeamTwoTricksScore int
	ID                 int
}

func (q *Queries) UpdateTrickScores(ctx context.Context, arg UpdateTrickScoresParams) error {
	_, err := q.db.Exec(ctx, updateTrickScores, arg.TeamOneTricksScore, arg.TeamTwoTricksScore, arg.ID)
	return err
}

const updateTurnScores = `-- name: UpdateTurnScores :exec
UPDATE trick SET team_one_turn_score = $1,team_two_turn_score=$2 WHERE trick_id = $3
`

type UpdateTurnScoresParams struct {
	TeamOneTurnScore int
	TeamTwoTurnScore int
	TrickID          int
}

func (q *Queries) UpdateTurnScores(ctx context.Context, arg UpdateTurnScoresParams) error {
	_, err := q.db.Exec(ctx, updateTurnScores, arg.TeamOneTurnScore, arg.TeamTwoTurnScore, arg.TrickID)
	return err
}
