// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BotUser struct {
	ID   int
	TgID string
}

type GamePlayer struct {
	PlayerID int
	GameID   int
	Team     int
}

type GuestPerson struct {
	ID        int
	UserID    int
	UidString string
}

type Hokm4Game struct {
	ID                 int
	TeamOneTricksScore int
	TeamTwoTricksScore int
	BetAmount          int
	CreatedStamp       pgtype.Timestamptz
	EndStamp           pgtype.Timestamptz
}

type Person struct {
	ID          int
	DisplayName pgtype.Text
	Bio         pgtype.Text
	Coin        int
	Created     pgtype.Timestamptz
}

type Trick struct {
	TrickID          int
	GameID           int
	Hokm             pgtype.Int8
	HakemIndex       int
	TeamOneTurnScore int
	TeamTwoTurnScore int
}

type Turn struct {
	TurnID  int
	TrickID int
	Moves   string
}

type UserStatistic struct {
	ID              int
	UserID          int
	Win             int
	Lose            int
	TotalTricksWon  int
	TotalTricksLost int
	TotalTurnsWon   int
	TotalTurnsLost  int
	UpdatedAt       pgtype.Timestamp
}
