// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GamePlayer struct {
	PlayerID int
	GameID   int
	Team     int
}

type Hokm4Game struct {
	ID                 int
	TeamOneTricksScore int
	TeamTwoTricksScore int
}

type PatchVersion struct {
	ID            int
	Rmode         string
	VersionNumber string
}

type Person struct {
	ID             int
	Created        pgtype.Timestamptz
	Username       string
	DisplayName    pgtype.Text
	HashedPassword string
	Bio            pgtype.Text
	Coin           int
}

type Trick struct {
	TrickID          int
	GameID           int
	Hokm             int
	HakemIndex       int
	TeamOneTurnScore int
	TeamTwoTurnScore int
}

type Turn struct {
	TurnID  int
	TrickID int
	Moves   string
}
