// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             int32              `db:"id" json:"id"`
	Created        pgtype.Timestamptz `db:"created" json:"created"`
	Username       string             `db:"username" json:"username"`
	DisplayName    pgtype.Text        `db:"display_name" json:"display_name"`
	HashedPassword string             `db:"hashed_password" json:"hashed_password"`
	Bio            pgtype.Text        `db:"bio" json:"bio"`
	Coin           pgtype.Int4        `db:"coin" json:"coin"`
}
