// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: person_query.sql

package sqldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCoinToPerson = `-- name: AddCoinToPerson :exec
UPDATE person
SET coin = coin + $1
WHERE id = $2
`

type AddCoinToPersonParams struct {
	Coin int
	ID   int
}

func (q *Queries) AddCoinToPerson(ctx context.Context, arg AddCoinToPersonParams) error {
	_, err := q.db.Exec(ctx, addCoinToPerson, arg.Coin, arg.ID)
	return err
}

const getGuestPersonByUid = `-- name: GetGuestPersonByUid :one
SELECT id, user_id, uid_string FROM guest_person WHERE uid_string = $1
`

func (q *Queries) GetGuestPersonByUid(ctx context.Context, uidString string) (GuestPerson, error) {
	row := q.db.QueryRow(ctx, getGuestPersonByUid, uidString)
	var i GuestPerson
	err := row.Scan(&i.ID, &i.UserID, &i.UidString)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, display_name, bio, coin, created FROM person
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPerson(ctx context.Context, id int) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Bio,
		&i.Coin,
		&i.Created,
	)
	return i, err
}

const getPersonStatisticsById = `-- name: GetPersonStatisticsById :one
SELECT id, user_id, win, lose, total_tricks_won, total_tricks_lost, total_turns_won, total_turns_lost, updated_at FROM user_statistic WHERE user_id = $1
`

func (q *Queries) GetPersonStatisticsById(ctx context.Context, userID int) (UserStatistic, error) {
	row := q.db.QueryRow(ctx, getPersonStatisticsById, userID)
	var i UserStatistic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Win,
		&i.Lose,
		&i.TotalTricksWon,
		&i.TotalTricksLost,
		&i.TotalTurnsWon,
		&i.TotalTurnsLost,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGuestPerson = `-- name: InsertGuestPerson :one
INSERT INTO guest_person (
    uid_string,user_id
  ) VALUES (
    $1,$2
  ) RETURNING id, user_id, uid_string
`

type InsertGuestPersonParams struct {
	UidString string
	UserID    int
}

func (q *Queries) InsertGuestPerson(ctx context.Context, arg InsertGuestPersonParams) (GuestPerson, error) {
	row := q.db.QueryRow(ctx, insertGuestPerson, arg.UidString, arg.UserID)
	var i GuestPerson
	err := row.Scan(&i.ID, &i.UserID, &i.UidString)
	return i, err
}

const insertPerson = `-- name: InsertPerson :one

INSERT INTO person (
  display_name,coin
) VALUES (
  $1,$2
)
RETURNING id, display_name, bio, coin, created
`

type InsertPersonParams struct {
	DisplayName pgtype.Text
	Coin        int
}

// -- name: GetPersonByUsername :one
// SELECT * FROM person
// WHERE username = $1 LIMIT 1;
func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, insertPerson, arg.DisplayName, arg.Coin)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Bio,
		&i.Coin,
		&i.Created,
	)
	return i, err
}

const insertUserStatistic = `-- name: InsertUserStatistic :one
INSERT INTO user_statistic (
  user_id
) VALUES (
  $1
) 
RETURNING id, user_id, win, lose, total_tricks_won, total_tricks_lost, total_turns_won, total_turns_lost, updated_at
`

func (q *Queries) InsertUserStatistic(ctx context.Context, userID int) (UserStatistic, error) {
	row := q.db.QueryRow(ctx, insertUserStatistic, userID)
	var i UserStatistic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Win,
		&i.Lose,
		&i.TotalTricksWon,
		&i.TotalTricksLost,
		&i.TotalTurnsWon,
		&i.TotalTurnsLost,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePersonDisplayName = `-- name: UpdatePersonDisplayName :exec
UPDATE person
SET display_name = $1
WHERE id = $2
`

type UpdatePersonDisplayNameParams struct {
	DisplayName pgtype.Text
	ID          int
}

func (q *Queries) UpdatePersonDisplayName(ctx context.Context, arg UpdatePersonDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updatePersonDisplayName, arg.DisplayName, arg.ID)
	return err
}

const updateUserStatistics = `-- name: UpdateUserStatistics :exec
UPDATE user_statistic
SET 
    win = win + $1,
    lose = lose + $2,
    total_tricks_won = total_tricks_won + $3,
    total_tricks_lost = total_tricks_lost + $4,
    total_turns_won = total_turns_won + $5,
    total_turns_lost = total_turns_lost + $6,
    updated_at = NOW()
WHERE user_id = $7
`

type UpdateUserStatisticsParams struct {
	Win             int
	Lose            int
	TotalTricksWon  int
	TotalTricksLost int
	TotalTurnsWon   int
	TotalTurnsLost  int
	UserID          int
}

func (q *Queries) UpdateUserStatistics(ctx context.Context, arg UpdateUserStatisticsParams) error {
	_, err := q.db.Exec(ctx, updateUserStatistics,
		arg.Win,
		arg.Lose,
		arg.TotalTricksWon,
		arg.TotalTricksLost,
		arg.TotalTurnsWon,
		arg.TotalTurnsLost,
		arg.UserID,
	)
	return err
}
