// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: person_query.sql

package sqldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPerson = `-- name: GetPerson :one
SELECT id, created, username, display_name, hashed_password, bio, coin FROM person
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPerson(ctx context.Context, id int) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.Bio,
		&i.Coin,
	)
	return i, err
}

const getPersonByUsername = `-- name: GetPersonByUsername :one
SELECT id, created, username, display_name, hashed_password, bio, coin FROM person
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetPersonByUsername(ctx context.Context, username string) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByUsername, username)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.Bio,
		&i.Coin,
	)
	return i, err
}

const insertPerson = `-- name: InsertPerson :one
INSERT INTO person (
  username,hashed_password
) VALUES (
  $1,$2
)
RETURNING id, created, username, display_name, hashed_password, bio, coin
`

type InsertPersonParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, insertPerson, arg.Username, arg.HashedPassword)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.Bio,
		&i.Coin,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :exec
UPDATE person
SET display_name = $1,
bio = $2
WHERE id = $3
`

type UpdatePersonParams struct {
	DisplayName pgtype.Text
	Bio         pgtype.Text
	ID          int
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) error {
	_, err := q.db.Exec(ctx, updatePerson, arg.DisplayName, arg.Bio, arg.ID)
	return err
}
