// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: telegram_query.sql

package sqldb

import (
	"context"
)

const insertBotUser = `-- name: InsertBotUser :one
INSERT INTO bot_user (
	tg_id
) VALUES (
	$1
) ON CONFLICT DO NOTHING
RETURNING id, tg_id
`

func (q *Queries) InsertBotUser(ctx context.Context, tgID string) (BotUser, error) {
	row := q.db.QueryRow(ctx, insertBotUser, tgID)
	var i BotUser
	err := row.Scan(&i.ID, &i.TgID)
	return i, err
}
