// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_query.sql

package sqldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, created, username, display_name, hashed_password, bio, coin FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.Bio,
		&i.Coin,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created, username, display_name, hashed_password, bio, coin FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.Bio,
		&i.Coin,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
  username,hashed_password
) VALUES (
  $1,$2
)
RETURNING id, created, username, display_name, hashed_password, bio, coin
`

type InsertUserParams struct {
	Username       string `db:"username" json:"username"`
	HashedPassword string `db:"hashed_password" json:"hashed_password"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.Bio,
		&i.Coin,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users 
SET display_name = $1,
bio = $2
WHERE id = $3
`

type UpdateUserParams struct {
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	Bio         pgtype.Text `db:"bio" json:"bio"`
	ID          int32       `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.DisplayName, arg.Bio, arg.ID)
	return err
}
