// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: version_query.sql

package sqldb

import (
	"context"
)

const getVersion = `-- name: GetVersion :one
SELECT id, rmode, version_number FROM patch_version WHERE rmode = $1 LIMIT 1
`

func (q *Queries) GetVersion(ctx context.Context, rmode string) (PatchVersion, error) {
	row := q.db.QueryRow(ctx, getVersion, rmode)
	var i PatchVersion
	err := row.Scan(&i.ID, &i.Rmode, &i.VersionNumber)
	return i, err
}

const insertVersion = `-- name: InsertVersion :one
INSERT INTO patch_version (version_number,rmode) VALUES ($1,$2)
RETURNING id, rmode, version_number
`

type InsertVersionParams struct {
	VersionNumber string `db:"version_number" json:"version_number"`
	Rmode         string `db:"rmode" json:"rmode"`
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) (PatchVersion, error) {
	row := q.db.QueryRow(ctx, insertVersion, arg.VersionNumber, arg.Rmode)
	var i PatchVersion
	err := row.Scan(&i.ID, &i.Rmode, &i.VersionNumber)
	return i, err
}

const updateVersion = `-- name: UpdateVersion :one
UPDATE patch_version SET version_number = $1 WHERE rmode = $2 
RETURNING id, rmode, version_number
`

type UpdateVersionParams struct {
	VersionNumber string `db:"version_number" json:"version_number"`
	Rmode         string `db:"rmode" json:"rmode"`
}

func (q *Queries) UpdateVersion(ctx context.Context, arg UpdateVersionParams) (PatchVersion, error) {
	row := q.db.QueryRow(ctx, updateVersion, arg.VersionNumber, arg.Rmode)
	var i PatchVersion
	err := row.Scan(&i.ID, &i.Rmode, &i.VersionNumber)
	return i, err
}
