name: GitHub Actions Demo
run-name: ${{ github.actor }} is updating release branch 🚀
on:
  push:
    branches:
      - release
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: build Core API
        working-directory: backend
        run: go build -o ./build/core ./cmd/core
    
      
      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H hcard.strangled.net >> ~/.ssh/known_hosts
        
      - name: Copy file to Vps
        working-directory: backend
        run: |
          scp -i ~/.ssh/id_rsa ./build/core arian@hcard.strangled.net:~/backend/core
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
