name: "godot-ci export"
on:
  push:
    branches:
        - "release"
env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: "android-pck"
  PROJECT_PATH: game
  
jobs:
  export-android:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
            mkdir -v -p ~/.local/share/godot/export_templates/
            mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/android
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-pack "AndroidPck" $EXPORT_DIR/pck/patch.pck
    