name: "godot-ci export"
# on:
#   workflow_dispatch:
#     inputs:
#       project_version:
#         required: true
#         type: string
on:
  push:
    branches:
        - "release"
env:
  GODOT_VERSION: 4.4.1
  GODOT_PROJRCT_LOCATION: ./game/project.godot
  EXPORT_FOLDER_ANDROID: build/android
  EXPORT_FOLDER_LINUX: build/linux
  APPLICATION_NAME: TixGame
  # EXPORT_NAME: "android-pck"
  
jobs:
  exports:
    runs-on: ubuntu-22.04
    container:
      image: debian:bookworm-slim
    
    steps:
      - name: setting env variable
        run: |
          echo "MAIN_FOLDER=$(pwd)" >> $GITHUB_ENV
      - name: install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends ca-certificates git git-lfs unzip wget tar zip adb openjdk-17-jdk-headless rsync && rm -rf /var/lib/apt/lists/*

      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        run: |
            wget -q -O godot_linux.zip https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}-stable/Godot_v${{env.GODOT_VERSION}}-stable_linux.x86_64.zip
            unzip godot_linux.zip
            mv Godot_v${{env.GODOT_VERSION}}-stable_linux.x86_64 godotcmd

            wget -q -O godot_export_template.tpz https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}-stable/Godot_v${{env.GODOT_VERSION}}-stable_export_templates.tpz
            mkdir -v -p ~/.local/share/godot/export_templates/${{env.GODOT_VERSION}}.stable
            unzip godot_export_template.tpz -d ~/.local/share/godot/export_templates/${{env.GODOT_VERSION}}.stable
            mv ~/.local/share/godot/export_templates/${{env.GODOT_VERSION}}.stable/templates/* ~/.local/share/godot/export_templates/${{env.GODOT_VERSION}}.stable/


      - name: Android pck
        run: |
          echo ${{env.MAIN_FOLDER}}/${{env.EXPORT_FOLDER_ANDROID}}
          mkdir -v -p ${{env.MAIN_FOLDER}}/${{env.EXPORT_FOLDER_ANDROID}}
          ./godotcmd ${{ env.GODOT_PROJRCT_LOCATION }} --headless --quiet --export-pack AndroidPck ${{env.MAIN_FOLDER}}/${{env.EXPORT_FOLDER_ANDROID}}/${{env.APPLICATION_NAME}}_android.pck
                
      - name: Upload PCK to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_REGION: us-east-1  # change to your region
        run: |
          apt-get install -y awscli
          aws s3 cp ${{env.EXPORT_FOLDER_ANDROID}}/${{env.APPLICATION_NAME}}_android.pck s3://${{ secrets.S3_BUCKET_NAME }}/patches/${{env.APPLICATION_NAME}}_android.pck
  
      # - name: Install Go
      #   run: |
      #     wget https://go.dev/dl/go1.22.2.linux-amd64.tar.gz
      #     tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz
      #     echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
      #     echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
      # - name: Run Go code
      #   run: |
      #     export PATH=$PATH:/usr/local/go/bin
      #     export S3_ACCESS_KEY
      #     export S3_BUCKET_NAME
      #     export S3_SECRET_KEY
      #     export S3_ENDPOINT

      #     cd backend 
      #     go run ./tools/gos3/.  # or go build, go test, etc.
      # - name: Android Pck Build
      #   run: |
      #     mkdir -v -p build/android/
      #     mkdir -v -p build/android/pck
      #     EXPORT_DIR="$(readlink -f build)"
      #     cd $PROJECT_PATH
      #     godot --headless --verbose --export-pack "AndroidPck" $EXPORT_DIR/pck/patch.pck
    