name: pipeline
on:
  push:
    branches:
        - "release"
  
permissions:
  packages: write
jobs:
  # run_tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.24.x'
  #     - name: Install dependencies
  #       run: go get .
  #     - name: Test with the Go CLI
  #       run: go test ./...
  
  build_and_push_image:
    runs-on: ubuntu-latest
    # needs:
      # - run_tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token:  ${{ secrets.read_token }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Core Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: core.Dockerfile
          tags: |
            ghcr.io/arian-nj/tix/core:latest
            ghcr.io/arian-nj/tix/core:${{ github.sha }}

      - name: Hokm4 Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: hokm4.Dockerfile
          tags: |
            ghcr.io/arian-nj/tix-hokm4:latest
            ghcr.io/arian-nj/tix-hokm4:${{ github.sha }}


  # deploy:
  #       runs-on: ubuntu-latest
  #       needs:
  #         - build_and_push_image
  #       steps:
  #       - name: Checkout code
  #         uses: actions/checkout@v4
  #         with:
  #           token:  ${{ secrets.read_token }}

  #       - name: create env file
  #         run: |
  #           echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

  #       - name: Docker Stack Deploy
  #         uses: cssnr/stack-deploy-action@v1
  #         with:
  #           name: hokmrun
  #           file: docker-stack.yaml
  #           host: hokm.filelord.ir
  #           user: filelord
  #           ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
  #           env_file: ./env.release
